Repository heclak/community-a4e-c, pull requests merged in 2019-01, with the labels that each got.

#47 Fixed animation ranges for RAT.
  A-4E-C/Cockpit/Scripts/Systems/electric_system.lua
Labels: 3d, code

#51 trim speed choice added
  A-4E-C/Cockpit/Scripts/Systems/trim.lua
  A-4E-C/Options/options.dlg
  A-4E-C/Options/optionsData.lua
  A-4E-C/Options/optionsDb.lua
Labels: Ready to Merge, code, enhancement

#59 Fixes rwr
  A-4E-C/Cockpit/Scripts/Systems/rwr.lua
  A-4E-C/Cockpit/Scripts/clickabledata.lua
  A-4E-C/Cockpit/Scripts/command_defs.lua
  A-4E-C/Cockpit/Scripts/mainpanel_init.lua
  A-4E-C/Input/joystick/Joystick - HOTAS Warthog.lua
  A-4E-C/Input/joystick/Throttle - HOTAS Warthog.lua
  A-4E-C/Input/joystick/default.lua
  A-4E-C/Input/keyboard/default.lua
  A-4E-C/Sounds/Effects/a4e-rwr-aaa-hi-loop.wav
  A-4E-C/Sounds/Effects/a4e-rwr-aaa-lo-loop.wav
  A-4E-C/Sounds/Effects/a4e-rwr-ai-loop.wav
  A-4E-C/Sounds/Effects/a4e-rwr-e-sam-hi-loop.wav
  A-4E-C/Sounds/Effects/a4e-rwr-e-sam-lo-loop.wav
  A-4E-C/Sounds/Effects/a4e-rwr-hum-loop.wav
  A-4E-C/Sounds/Effects/a4e-rwr-i-sam-lo-loop.wav
  A-4E-C/Sounds/sdef/a4e-rwr-aaa-hi-loop.sdef
  A-4E-C/Sounds/sdef/a4e-rwr-aaa-lo-loop.sdef
  A-4E-C/Sounds/sdef/a4e-rwr-ai-loop.sdef
  A-4E-C/Sounds/sdef/a4e-rwr-e-sam-hi-loop.sdef
  A-4E-C/Sounds/sdef/a4e-rwr-e-sam-lo-loop.sdef
  A-4E-C/Sounds/sdef/a4e-rwr-hum-loop.sdef
  A-4E-C/Sounds/sdef/a4e-rwr-i-sam-lo-loop.sdef
Labels: Ready to Merge, code
